version: '3.8'
services:
  bitwarden-to-keepass:
    build: .
    command: bash -c 'export BW_SESSION=`$BW_PATH login --raw` && python3 bitwarden-to-keepass.py && $BW_PATH lock'
    volumes:
      - ./exports:/exports
    tmpfs:
      - /tmp
      - '/root/.config/Bitwarden CLI'
    env_file:
      - .env
